name: ShopGUIPlusExtension
main: com.dorito.shopguiplusextension.Main
version: 1.0
api-version: 1.12
commands:
  spawnerconfirm:
    description: Confirms Spawner purchase.
    usage: /<command> <args>

